In [3]:
import pandas as pd
from sklearn.model_selection import KFold, train_test_split
import numpy as np
import os

In [2]:
def split_data(algorithm_name,dim,seed):
    file_name=f'{algorithm_name}_dim_{dim}_seed_{seed}'
    df = pd.read_csv(f'algorithm_run_data/{file_name}.csv',index_col=[0],compression='zip')
    kf = KFold(n_splits=10)
    instance_ids=np.array(df['instance_id'].drop_duplicates())
    output_dir=os.path.join('folds','trajectory_problem_classification',file_name)
    os.makedirs(output_dir, exist_ok=True)
    fold=0
    for train_index, test_index in kf.split(instance_ids):
        train_ids,test_ids=instance_ids[train_index], instance_ids[test_index]
        train_ids,val_ids=train_test_split(train_ids, test_size=0.1)
        print(test_ids)
        for split_ids,split_name in [(train_ids,'train'),(val_ids,'val'),(test_ids,'test')]:
            pd.DataFrame(split_ids).to_csv(os.path.join(output_dir,f'{split_name}_{fold}.csv'))
        fold+=1
    
    

In [3]:
for algorithm in ['DE','ES','PSO']:
    for seed in [200,400,600,800,1000]:
        split_data(algorithm,5,seed)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]
[71 72 73 74 75 76 77 78 79 80]
[81 82 83 84 85 86 87 88 89 90]
[ 91  92  93  94  95  96  97  98  99 100]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]
[71 72 73 74 75 76 77 78 79 80]
[81 82 83 84 85 86 87 88 89 90]
[ 91  92  93  94  95  96  97  98  99 100]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]
[71 72 73 74 75 76 77 78 79 80]
[81 82 83 84 85 86 87 88 89 90]
[ 91  92  93  94  95  96  97  98  99 100]
[ 1  2  3 

In [9]:
kf = KFold(n_splits=10)
instance_ids=np.array(list(range(1,101)))
output_dir=os.path.join('folds','problem_classification_100_instances')
os.makedirs(output_dir, exist_ok=True)
fold=0
for train_index, test_index in kf.split(instance_ids):
    train_ids,test_ids=instance_ids[train_index], instance_ids[test_index]
    train_ids,val_ids=train_test_split(train_ids, test_size=0.1)
    print(test_ids)
    for split_ids,split_name in [(train_ids,'train'),(val_ids,'val'),(test_ids,'test')]:
        pd.DataFrame(split_ids).to_csv(os.path.join(output_dir,f'{split_name}_{fold}.csv'))
    fold+=1

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]
[51 52 53 54 55 56 57 58 59 60]
[61 62 63 64 65 66 67 68 69 70]
[71 72 73 74 75 76 77 78 79 80]
[81 82 83 84 85 86 87 88 89 90]
[ 91  92  93  94  95  96  97  98  99 100]


In [7]:
instance_ids[list(train_index)]

TypeError: list indices must be integers or slices, not list